### ISSUE TITLE
Add unnumbered interface support to Cumulus

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#101]
Cumulus VX configuration templates do not include unnumbered IPv4 or IPv6 interfaces. Fix that.

**Comment by petercrocker** [comment]
I've just created a PR to add this platform support: https://github.com/ipspace/netsim-tools/pull/155

**Comment by ipspace** [comment]
Thank you. 

Integration tests ran fine, managed to get VX to talk to everyone else. Amended the commit (as explained in #155).
