### ISSUE TITLE
Update SR OS initial template to match the new addressing data structures

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#108]
SR OS supports unnumbered interface, but only using the old **unnumbered** attribute. @jbemmel please update it to use the new per-AF unnumbered settings. I can't test it, and I'm afraid I might bork it.

Here's the boilerplate template used in most other devices:

```
{#
    IPv4 addresses
#}
{% if 'ipv4' in l %}
{%   if l.ipv4 == True %}
 ip unnumbered Loopback0 poll
{%   elif l.ipv4|ipv4 %}
 ip address {{ l.ipv4|ipaddr('address') }} {{ l.ipv4|ipaddr('netmask') }}
{%   else %}
! Invalid IPv4 address {{ l.ipv4 }}
{%   endif %}
{% endif %}
{#
    IPv6 addresses
#}
{% if 'ipv6' in l %}
{%   if l.ipv6 == True %}
 ipv6 enable
{%   elif l.ipv6|ipv6 %}
 ipv6 address {{ l.ipv6|upper }}
{%   else %}
! Invalid IPv6 address {{ l.ipv6 }}
{%   endif %}
{% endif %}
```

As we know IPv4/IPv6 addresses are valid you could use a simpler approach -- test for `l.ipv4|ipv4` and `l.ipv6|ipv6` -- but while that works in `template` most Ansible configuration modules start spewing out warnings when a boolean is sent through an ipaddr filter.

**Comment by jbemmel** [comment]
See https://github.com/ipspace/netsim-tools/pull/114

**Comment by ipspace** [comment]
Thanks a million - that was really fast. Closing this one...
