### ISSUE TITLE
Add BFD support for Junos (interface, OSPF, IS-IS)

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#109]
Junos configuration templates don't support BFD yet. We need a BFD configuration module (to set global and interface parameters) and BFD parameters in OSPF and IS-IS configuration templates.

**Comment by ipspace** [comment]
Implementer notes @ https://github.com/ipspace/netsim-tools/blob/dev/docs/dev/bfd.md

**Comment by ssasso** [comment]
It seems that BFD on Junos is configurable only on a per-protocol basis, i.e. https://www.juniper.net/documentation/us/en/software/junos/high-availability/topics/example/ospf-bfd-configuring.html

Trying to address the initial support for OSPF in a dedicated PR.

**Comment by ipspace** [comment]
> It seems that BFD on Junos is configurable only on a per-protocol basis

Not a problem. Thanks a million for the additions!
