### ISSUE TITLE
Incorrect IS-IS network type on multi-access unnumbered interfaces

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#112]
Some IS-IS implementations work just fine on unnumbered multi-access interfaces, but we should not set **isis network-type point-to-point** on such interfaces.

Configuration templates should check `l.neighbors|default([])|length == 1` to set **isis network-type point-to-point**

**Comment by ipspace** [comment]
@jbemmel Apologize for the extra work :(

The old templates still work as long as the user doesn't play with link **type** attribute, but I preferred to have a cleaner solution (checking the number of neighbors).

Also, IS-IS works just fine on multi-access unnumbered links (on IOS and EOS), and setting **point-to-point** on those links breaks stuff (which is how I found out this bug in the first place).

**Comment by jbemmel** [comment]
Similar to https://github.com/ipspace/netsim-tools/issues/123 I think it would make sense if this logic were added to the isis.py module?

**Comment by ipspace** [comment]
Sure. That's the next step ;) Want to wait with the template fixes until I get it done?

**Comment by ipspace** [comment]
Implemented in 0e19e541f50927908fddf34afa41d0464f8541a2
