### ISSUE TITLE
Missing IPv6 IS-IS metric

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#113]
In multi-topology IS-IS setup, IPv4 and IPv6 use different metrics. Configuration templates have to set both based on whether IPv6 used by IS-IS.

**Comment by ipspace** [comment]
@jbemmel Please check whether this applies to SR/OS or SR/Linux. All other IS-IS implementations apart from FRR needed two IS-IS metrics (one for default topology, one for IPv6 topology)

**Comment by jbemmel** [comment]
I checked but I didn't see separate settings per AF (but I am no expert in this area)

**Comment by ipspace** [comment]
Thank you! We can always fix it later if needed.

**Comment by jbemmel** [comment]
Added https://github.com/ipspace/netsim-tools/pull/129/files which fixes IS-IS ipv6 metrics for SROS
