### ISSUE TITLE
Pre-calculate OSPF parameters to simplify configuration templates

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#123]
It makes no sense to have a dozen configuration templates with the same convoluted test saying "is this a passive interface" or "is OSPF disabled on this interface"

**ospf.py** should calculate all necessary interface parameters (including OSPF area propagation from node into interfaces) making the templates extremely easy to write.

Here's the basic idea:

* If an interface does not have **ospf** attribute then OSPF does not run on it (solves the "external interfaces" test)
* An interface with **ospf.passive** is... guess what... passive ;)
* **ospf.network** is set to **point-to-point** when needed. This would also allow users to play with other OSPF network types.

**Comment by ipspace** [comment]
Implemented for Cumulus, Arista, FRR, IOS, NXOS and Junos.

@ssasso @jbemmel @petercrocker It would be nice if other templates could also get fixed, but it's not mandatory.

Notes on using network types:
* Values of **network_type** attribute are checked, you can expect one of the four valid values
* If your device allows P2P configuration but nothing else, see Arista EOS template
* If your device uses different set of keywords, see Junos template
* If you can't configure broadcast network type, see Arista (explicit **no ip ospf network**) or Junos (skipped command) template

**Comment by ssasso** [comment]
I will do during the next week, can you keep the PR open until that?

**Comment by jbemmel** [comment]
SROS supports the following OSPF interface types: broadcast|non-broadcast|point-to-point|secondary

Regarding 'secondary': See https://www.juniper.net/documentation/en_US/junos/topics/topic-map/ospf-multiarea-adjacency.html - we may have to refine the model to support multi-area adjacencies in the future

**Comment by ipspace** [comment]
@ssasso No worries, I'll merge your changes whenever you'll have them ready.

@jbemmel At a certain point we'll have to draw the line -- it doesn't make sense to support every quirk ever invented in the IETF. We should keep the core simple and stable, and encourage people to use plugins to extend the tool in any direction they wish. I already have the infrastructure for "contributed plugins".

**Comment by jbemmel** [comment]
@ipspace agreed, I was merely putting a 'note to self' in the context of this OSPF discussion. 

As you are writing the documentation, you may want to add a note that 'multiarea' adjacencies are not supported. Happy to draw a line there

**Comment by ssasso** [comment]
@ipspace It was easier than I thought ;)

**Comment by ipspace** [comment]
As it should be -- there's a reason we moved all the logic into Python ;)
