### ISSUE TITLE
Host versus Router devices

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#139]
We already support "host" devices (that don't do IP forwarding) -- Linux VMs or containers. Currently we hack our way through Linux routing setup installing a default route to the first IP address on the link, which could easily fail if we connect multiple Linux devices to the same segment.

To start with, we need a flag saying "this device is a host", for example **role: host** (or **router** or **bridge**) in node data. Based on that, the transformation code could:

* Set **stub** role on all links that have a single router attached (no-brainer default behavior)
* Set **stub** role or **passive** flag on all links/interfaces that have hosts attached to prevent routing protocols running on host-attached links -- this should probably be configurable in routing protocols.

The link transformation code should also set **gateway** attribute on every link with attached hosts. Please note that this is not yet FHRP like VRRP. That should be a separate configurable module.

The **gateway** would then be copied into interface data (default) and could be used as the next hop for IPv4 routes on hosts.

@jbemmel @ssasso: Any comments or ideas? In particular, should we do this for IPv4 only and rely on RA for IPv6 (preferred solution from my perspective) or have multi-AF gateway attributes?

**Comment by ipspace** [comment]
@ssasso @jbemmel @petercrocker: host devices (linux) no longer have a loopback interface (which wouldn't be reachable anyway), you might want to fix the initial configuration templates.

The existing initial configuration templates will continue to work but will not include **ip host** (or equivalent) commands for hosts. You can find sample code for devices that support more than one address per host in `ios.j2` or `eos.j2`, for devices that support single address per host in `nxos.j2` and for Linux in `linux.j2` or `cumulus.j2`.

I fixed the configuration templates for Linux, Cumulus v4, FRR, IOS, NXOS and EOS. Have no idea how to do that for Junos (@petercrocker -- help much appreciated).

**Comment by petercrocker** [comment]
Added for Junos: https://github.com/ipspace/netsim-tools/pull/186
