### ISSUE TITLE
Fix the inheritance of module settings into node data

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#141]
We already support four levels of node-level module settings:

* Explicit node data (**nodes.r1.ospf.area**)
* Global defaults (**ospf.area**)
* System defaults (**defaults.ospf.area**)
* Device defaults (**defaults.devices._type_.ospf.area**) -- currently used only for **sr** module

The current precedence is for calculating node module settings is:

* Node data
* Global defaults
* Device defaults

The problem: system defaults get merged into global defaults before the module node data is calculated, effectively disabling device defaults.

Correct precedence:

* Node data
* Global defaults
* Device defaults
* System defaults

Global defaults have to be adjusted _after_ the node data has been adjusted.

**Comment by jbemmel** [comment]
Given https://github.com/ipspace/netsim-tools/commit/a490d814fbffa460042004f16a045b01c1964dee is this still an issue?

**Comment by ipspace** [comment]
It was. Fixed by 038a797. Closing
