### ISSUE TITLE
'netlab down' missing a provider option

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#144]
When I use the 'clab' provider using 'netlab up -p clab', things work fine.

However, when I try to take down the same lab, it fails because the 'kvm-ok' probe fails (I don't have libvirt installed).
'down' needs to support the same set of CLI options as 'up'

**Comment by ipspace** [comment]
**netlab down** needs to know which provider you're using. I'm guessing that you used `-p` flag when starting the lab (or something similar), and at the moment that information is not saved anywhere, so **netlab down** takes the default setting (_libvirt_).

Adding **provider: clab** to the network topology file will solve the problem, or we could add `-p` flag to **netlab down**, but then someone will forget that and complain, or we could create a snapshot of the transformed data structure and use that in **netlab down**.

Any preference?

**Comment by jbemmel** [comment]
I was replicating https://blog.ipspace.net/2022/01/ospf-unnumbered.html using SROS and clab, so I used
```
netlab up -d sros -p clab -v
```

To me this ability to use a topology unmodified while overriding certain settings is a key feature, my preference would be to make 'netlab down' accept the same parameters as 'netlab up' (using the same parsing logic)

**Comment by ipspace** [comment]
👍
