### ISSUE TITLE
SRv6: core module or plugin?

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#146]
I have created a basic srv6 module supporting sros, I could document it and submit it or leave it as a one-off plugin in an example.

Preference?

**Comment by jbemmel** [comment]
For the BGP anycast example it makes sense to me to build it as a plugin, but srv6 is different enough (in my mind) to warrant its own module. Besides, we already have 'sr' as a module, so having 'srv6' as something else would be confusing

**Comment by ipspace** [comment]
OK, go for it ;)
