### ISSUE TITLE
IS-IS on vSRX error: IncorrectValue in interfaces

### ISSUE THREAD

**Issue by petercrocker** [ipspace/netsim-tools#149]
Just noticed a regression. When booting the latest 1.1 release with the attached network config file, the logic validating the network topology incorrectly flags vsrx as not being able to run unnumbered for IS-IS:

```IncorrectValue in interfaces: Device vsrx used on node r1 cannot run IS-IS over unnumbered ipv4 interfaces```

I'll try and figure out the new unnumbered code when I can and solve this, but wanted to get this logged.

Example config:
#
# libvirt lab simulating a MPLS backbone and two eBGP peers
#
---
addressing:
  p2p:
    unnumbered: true
  loopback:
    ipv6: 2001:db8:cafe::/48

defaults:
  device: vsrx

module: [bgp, isis]

groups:
  as65000:
    config: [junos_sr.j2]

bgp:
  as_list:
    65000:
      members: [r1, r2, r3, r4, r5, r6, r7, r8, c1, c2, c3]
    65100:
      members: [ext1]
    65200:
      members: [ext2]

nodes:
  ext1:
    module: [bgp]
    bgp:
      originate:
        - "172.16.0.0/19"
  ext2:
    module: [bgp]
    bgp:
      originate:
        - "172.17.0.0/19"
  r1:
  r2:
  r3:
  r4:
  r5:
  r6:
  r7:
  r8:
  c1:
  c2:
  c3:

links:
  - ext1:
    r1:
    prefix: 10.10.10.0/24
  - r1-r2
  - r1-r8
  - r1-c1
  - r2-c1
  - r8-c1
  - c1-r3
  - c1-r7
  - c1-c2
  - r3-c2
  - r7-c2
  - c2-r4
  - c2-r6
  - c2-c3
  - r4-c3
  - r6-c3
  - r4-r5
  - r6-r5
  - c3-r5
  - r5:
    ext2:
    prefix: 10.10.11.0/24

**Comment by jbemmel** [comment]
See https://github.com/ipspace/netsim-tools/blob/master/netsim/topology-defaults.yml#L361

Try adding 'ipv4: True' there

**Comment by petercrocker** [comment]
Nice thanks @jbemmel you saved me looking around! I’ll submit a PR for this.

**Comment by ipspace** [comment]
You guys are awesome. Thanks a million (waiting for PR).

On a tangential note - looks like we should wait a bit before implementing new functionality as there might be a few other bugs lurking out there that we better release quickly as 1.1.1.

**Comment by ipspace** [comment]
OTOH, I did try to run unnumbered IS-IS on vSRX and it did not work, that's why I removed "ipv4: True" from there. If it works for you, please send me the details, I have to fix a blog post that's going to be published next week.

**Comment by petercrocker** [comment]
@ipspace the topology above spins up just fine (assuming an older netsim release or this change), been doing SR on it constantly for a week, and looking at TED info in IS-IS, all unnumbered. I can send some outputs if you don’t want to spin it up.

**Comment by ipspace** [comment]
In my case I got it all up and running, IS-IS worked, but IPv4 forwarding tables were not populated (due to missing ARP glue). Please note that was a multi-vendor setup (tests/integration/multivendor-isis-bfd.yml), if you got IPv4 forwarding tables populated without SR (which could be a totally different story), please let me know.

**Comment by ipspace** [comment]
I don't know what I was looking at. I'm pretty sure I didn't see IS-IS IPv4 routes on vSRX, but today they are there... Fixed the default settings in 51ede3cfb7a32ddc83b99547763c93322bb1a1cd

Apologize for the confusion!
