### ISSUE TITLE
NANOG84 Hackathon (Feb 4th)

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#150]
See https://www.nanog.org/events/nanog-84-hackathon/ - "self-organize into teams to work on software passion projects"

I have registered, and will be travelling to Austin for this event. I think it could be a great opportunity to do something with Netsim-Tools

**Comment by ipspace** [comment]
Sounds like a great idea, but the hours are brutal (from where I sit). We could make it work if you take the lead and I just sit in the background until I fall off the chair (or someone declares me brain-dead and sends me off to sleep).

**Comment by petercrocker** [comment]
I'm game, but like Ivan since I'm so time-shifted not sure how much I'll really be able to work on this.

**Comment by jbemmel** [comment]
My Hackathon project will be about building a multi-vendor NAPALM driver using  gNMI. I may still end up showing off Netsim-Tools, we'll see
