### ISSUE TITLE
Code Development: Agreed linters/formatters

### ISSUE THREAD

**Issue by petercrocker** [ipspace/netsim-tools#157]
Hey @ipspace the next changes I'm going to make are for ebgp unnumbered on cumulus, and as i've had to start making changes to some python code for the first time. Which brings up auto-formatters. The moment I've changed a .py file, it's formatted it completely differently to how it was before. And I've been trying to reverse engineer what python formatter you've been using, and it's settings, but I am having no luck. 

So this is a request to know what python (and any other language) linters/formatters you'd like the code to be processed by, and any settings that are non-default, so I don't screw up diffs during code review. Thanks!

**Comment by ipspace** [comment]
Did you have to open that particular can of worms 🤣 To start with: I don't use a formatter -- never used one in my life, and I'm too set in my ancient ways, but maybe I could be persuaded ;)

Looking through your changes:

* I have absolutely no problem with having consistent quotes, and I really don't care whether they are single quotes or double quotes
* I don't like "space after comma"
* I could live with "no space around brackets". Interestingly, I don't mind curly brackets as much as I mind square ones, but I'm OK with whatever
* Rolling a long function call into a single line ~is disgusting~ makes it completely unreadable (line 122 in bgp.py in your PR). I know it's hard to standardize this one, as I also think going for one-parameter-per-line in all cases decreases code readability, but I'd like to keep calls to the same function (common.error in this case) formatted the same way.

So what we're looking for is a formatter/linter setting that would ignore or not touch a lot of things opinionated formatters/linters love to mess up.

We can start by trying to make your formatter "behave". What are you using?

**Comment by petercrocker** [comment]
I've just gone with **don't change the formatting** for now :)
