### ISSUE TITLE
Unnumbered ipv4 incompatible with static ipv6 (sros)

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#160]
On SROS, one cannot configure the combination of an unnumbered ipv4 address with a numbered ipv6 address; ipv6 needs to be unnumbered too in that case.

Is this common for other platforms, or limited to SROS?
```
MINOR: MGMT_CORE #4001: configure router "Base" interface "i1/1/c1" ipv4 unnumbered ip-address 
- Unnumbered configuration not compatible with IPv6 address configuration - configure router "Base" interface "i1/1/c1"

*(gl)[/configure router "Base" interface "i1/1/c1"]
A:admin@r0# info
    admin-state enable
    description "r0 ~ r1 ()"
    port 1/1/c1/1
    ipv4 {
        unnumbered {
           system
        }
    }
    ipv6 {
        address 2001:1::1 {
            prefix-length 64
        }
    }
```

**Comment by petercrocker** [comment]
On Cumulus, you can have static on IPv6 and unnumbered on IPv4. Whether you’d want this is a different story ;)

For example, how to configure OSPF (v2) unnumbered on that platform is to configure the loopback IP address also on the physical Ethernet interface

auto lo
  ip address 10.0.0.1

auto swp1
  ip address 10.0.0.1

Then you could put whatever IPv6 address on swp1 if you wanted.

**Comment by ipspace** [comment]
Never encountered anything similar. Seems to be SROS quirk.
