### ISSUE TITLE
Platforms: Implement NVUE for Cumulus Linux releases >= 5.0

### ISSUE THREAD

**Issue by petercrocker** [ipspace/netsim-tools#161]
Cumulus Linux versions 5.0 and greater default to a new model-driven schema for configuration called NVUE: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux/System-Configuration/NVIDIA-User-Experience-NVUE/

If a user of netsim-tools downloads a Cumulus image <= 4.4.0, it can use the classic `net` commands or `vtysh` for configuration. 

If a user downloads Cumulus >= 5.0.0, the `nv` commands are the only method supported.

This issue is to track development of support for spinning up and configuring Cumulus via NVUE.

**Comment by petercrocker** [comment]
Round one of this is coded up. Still need to do testing, create test cases, and work out any bugs:
https://github.com/petercrocker/netsim-tools/tree/nvue

**Comment by ipspace** [comment]
This is awesome -- when thinking about two parallel configuration methods, I wanted to say "wouldn't it be easier if we create another device", and you did just that ;)

One of the things on my to-do list is to create parameter inheritance across devices (example: IOSv and CSR). When that's done, you'll be able to keep most settings common (if it makes sense) and just specify the changes.

**Comment by jbemmel** [comment]
Agreed, nice job! I'm thinking I may want to do something similar for sros_openconfig

**Comment by petercrocker** [comment]
Having two different devices isn’t ideal. For example, if a user just let’s vagrant download the publicly available cumulus box, it’s up to the user to look at what version of OS it is, know if it’s old vtysh method or new NVUE method, and then configure it appropriately. Since Cumulus did a clean break (>= 4.4.0 is old method, <= 5.0.0 is NVUE) I think it would be better if we only have one Cumulus “device” and auto-detect which config method to use. Because they’ll never be parallel (possibly unlike the SROS case where you can choose parallel config methods).

**Comment by petercrocker** [comment]
But for now it’s good for testing to keep it separate. I’m still working through a whole new set of vendor quirks. It’s a brand spanking new schema, and I’m sure some of it makes sense to the developer… I can set OSPF area on a physical switch interface, but if I want to set the OSPF area for a loopback, I’ve got to use a network statement. And if I want to bgp send-community, they’re called “regular” and “extended” not “standard” and “extended” like every other vendor, and there’s no “both” option so I’m in jinja2 land doing hacks… </rant>

**Comment by ipspace** [comment]
> With that in mind, I think making cumulus “just work” is a better approach than two different device definitions.

Agreed. Once you feel NVUE method is ready to roll out we should switch the device types (**cumulus** becomes **cumulus:5.0**), but since we already have old-style cumulus config methods, and someone might want to play with cumulus 4.x (or explore more traditional Linux networking), it might make sense to rename current **cumulus** device into **cumulus4** or something. Obviously we would stop adding new functionality to cumulus4 at that point.

**Comment by petercrocker** [comment]
>  it might make sense to rename current **cumulus** device into **cumulus4** or something. Obviously we would stop adding new functionality to cumulus4 at that point.

Great idea. I'll let you know when I think that time is. Honestly I'd say it'll be months at least, since the 5.0 release only just came out, and the only people who will be using it will be the cutting edge cumulus customers who will be starting their testing. So when I think the cumulus nvue code is ready, we can merge it, and document it appropriately as a different device, and not the cumulus standard.

**Comment by petercrocker** [comment]
This can be closed once this PR is reviewed and merged:
https://github.com/ipspace/netsim-tools/pull/172
