### ISSUE TITLE
Platform caveats for platforms using nokia.grpc collection

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#168]
nokia.grpc Ansible collection is identified as a prerequisite for SR OS in caveats.md. Looks like SR Linux uses the same collection, so it might be worth adding that to the caveats.

Furthermore, nokia.grpc does not work without additional Python modules, and I can't find the list of prerequisites anywhere; it might be worth adding them to caveats.md. At the moment, someone trying to take SR Linux for a drive has a hard time figuring out how to do that.

**Comment by ipspace** [comment]
It must be me being too stupid to use it. Tried installing **protobuf** and **grpcio** based on error messages, now I'm getting

![image](https://user-images.githubusercontent.com/16917911/150396789-76bc3b34-510c-457a-8222-ddea90c0566e.png)

**Comment by jbemmel** [comment]
Created an issue to see if we can automate this better: https://github.com/nokia/ansible-networking-collections/issues/22

**Comment by ipspace** [comment]
Installed those two modules, and even switched to Python 3.9 just in case. Same problem. I have no idea what's going on, the crash is somewhere deep within Ansible:

```
The full traceback is:
  File "/tmp/ansible_nokia.grpc.gnmi_config_payload_38gjc0au/ansible_nokia.grpc.gnmi_config_payload.zip/ansible_collections/nokia/grpc/plugins/modules/gnmi_config.py", line 135, in main
  File "/tmp/ansible_nokia.grpc.gnmi_config_payload_38gjc0au/ansible_nokia.grpc.gnmi_config_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [s1]: FAILED! => changed=false
  code: -32603
  invocation:
    module_args:
      backup: false
      backup_options: null
      delete: []
      prefix: null
      replace: []
      update:
      - path: interface[name=lo0]/subinterface[index=0]
        val:
          ipv4:
            address:
            - ip-prefix: 10.0.0.1/32
              primary:
              - null
      - path: interface[name=system0]/subinterface[index=0]
        val:
          ipv4:
            address:
            - ip-prefix: 10.0.0.1/32
      - path: interface[name=ethernet-1/1]
        val:
          description: s1 ~ s2
          subinterface:
            index: 0
            ipv4:
              address:
              - ip-prefix: 10.1.0.1/30
                primary:
                - null
      - path: interface[name=lo0]
        val:
          description: Stub interface
          subinterface:
            index: 2
            ipv4:
              address:
              - ip-prefix: 172.16.0.1/24
                primary:
                - null
      - path: interface[name=ethernet-1/3]
        val:
          description: s1 ~ s2,s3
          subinterface:
            index: 0
            ipv4:
              address:
              - ip-prefix: 172.16.2.1/24
                primary:
                - null
      - path: network-instance[name=default]
        val:
          interface:
          - name: lo0.0
          - name: ethernet-1/1.0
          - name: lo0.2
          - name: ethernet-1/3.0
          type: default
  msg: dictionary keys changed during iteration
```

**Comment by ipspace** [comment]
... switched to Ansible 2.9.1 just in case. No change.

**Comment by jbemmel** [comment]
For some reason the Galaxy collection package doesn't have this fix: https://github.com/jbemmel/ansible-networking-collections/commit/c7e91ec6cca279b021094c1e97b15b0f9220b294#diff-ea47a30f249ea178576accb5b7cd997685bc195e3ce162518717d219ed77ea8c

**Comment by ipspace** [comment]
Thanks a million for figuring this out -- of course it works now. Another few hours of my life irretrievable lost chasing ghosts :( 

Please let me know when the public packages needed to run SR Linux get to the point where one can download them and run one of the SR Linux examples out-of-the-box. I would love to blog about your examples in `netsim-examples` repo, but it makes no sense if they are not reproducible.
