### ISSUE TITLE
Minimum supported Ansible version

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#178]
The current documentation claims that you need Ansible 2.9.1 with _netsim-tools_. Recent PR #172 broke that assumption with FQDN module name for an internal module.

Not everyone, including Ubuntu and (surprise, surprise) Red Hat is keen on flip-floping Ansible packaging ~shenanigans~ experiments, so it's safe to assume a non-zero percentage of our users would still be on 2.9.

> You are reading the latest community version of the Ansible documentation. Red Hat subscribers, select 2.9 in the version selection to the left for the most recent Red Hat release.

Any thoughts @jbemmel @petercrocker? Should we make Ansible 2.9 support mandatory for the moment?

**Comment by petercrocker** [comment]
I’m fine modding the playbooks i submitted to remove the FQDN. I’ve gotten in the habit of it from a recent project so we didn’t have to worry about things breaking in the long run, but no real reason to force people to deal with the new world of a different ansible each week…

**Comment by jbemmel** [comment]
I hit an issue with 2.9.0, so I would suggest to stay with 2.9.1 (release Date: 2019-11-13) for now

**Comment by ipspace** [comment]
2.9.1 is recommended in the documentation. The only thing we have to do is not to use FQDN for internal modules.

@petercrocker will you fix the Cumulus tasks or should I do that?

**Comment by petercrocker** [comment]
I’ll fix it tomorrow @ipspace . I’ve got some fortinet cleanup to do as well with the recent changes.

**Comment by ipspace** [comment]
👍 Thank you!

**Comment by petercrocker** [comment]
Fixed for cumulus and cumulus_nvue: https://github.com/ipspace/netsim-tools/pull/185
