### ISSUE TITLE
Minimal Python version 3.7

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#190]
Due to the use of e.g. 'capture_output' for subprocess.run, Netsim-Tools fails when using Python 3.6 or below

Can we specify/enforce the minimal required Python version?

**Comment by ipspace** [comment]
Absolutely. Python 3.7 seems to be a good choice.

If you know how to fix setup.py that would be most appreciated, otherwise I'll start digging ;)

**Comment by jbemmel** [comment]
```
from setuptools import setup

setup(
    # Your setup arguments
    python_requires='>=3.7',  # Your supported Python ranges
)
```
