### ISSUE TITLE
Add gNMI dependencies to 'netsim install'

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#206]
The instructions are fairly clear, but it remains a bit cumbersome to install the dependencies for gNMI

Can we add 'gnmi' as an install target?

**Comment by ipspace** [comment]
Absolutely. I would also add the installation of Nokia Ansible collection (maybe without error checking just in case the GitHub repo goes away).

Please fix the installation scripts in netsim/install and submit a PR. Thank you!

**Comment by ipspace** [comment]
Implemented in #360.
