### ISSUE TITLE
CSR1000v doesn't boot when building image

### ISSUE THREAD

**Issue by kbreit** [ipspace/netsim-tools#209]
I am trying to build a CSR1000v image using `netlab libvirt package csr  imagename.qcow2` and it's stalling at

```
BOOT CMD: /packages.conf rw root=/dev/ram max_loop=64 HARDWARE=virtual
VMCONSOLE quiet console= SR_BOOT=bootflash:packages.conf
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   e56bb60e:59aaa5ab:3a67cbe2:5a3e9aa6:6c1d6e93
        expected     e56bb60e:59aaa5ab:3a67cbe2:5a3e9aa6:6c1d6e93
package header rev 3 structure detected
IOSXE version 17.3.04a detected
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   9dfce1eb:17df3f84:e13a1c6a:9f7af15e:d184acd3
        expected     9dfce1eb:17df3f84:e13a1c6a:9f7af15e:d184acd3
Package type:0x7531, flags:0x0
linux image, size=0x688dc8
linux isord, size=0x279f01a

Feb 17 17:20:46.723: %BOOT-5-OPMODE_LOG: R0/0: binos: System booted in AUTONOMOUS mode
```

17.3.04a IOS-XE on Ubuntu 20.04 hosted on ESXi. VM has 4 CPUs and 8 GB RAM.

**Comment by ipspace** [comment]
Did you download the image with "serial" in the name (so it's trying to communicate via the serial port)?

If you did, then there's something weirdly wrong with your system. The only thing **netlab** is doing here is launching:

```
virt-install --connect=qemu:///system --name=vm_box --os-type=linux --os-variant=rhel4 --arch=x86_64 --cpu host --vcpus=1 --hvm \
          --ram=4096 --disk path=vm.qcow2,bus=ide,format=qcow2 --network=network:vagrant-libvirt,model=virtio --graphics none --import
```

That's as simple as it gets: start a KVM virtual machine off QCOW2 disk image.

**Comment by ipspace** [comment]
If you have GUI interface access to the Ubuntu VM then you can use this recipe:

https://codingpackets.com/blog/cisco-iosv-vagrant-libvirt-box-install/

I'm SSH-ing into my Ubuntu server, so it didn't work for me, but I'll add a pointer to the installation instructions.

**Comment by kbreit** [comment]
I downloaded the serial version and it seems to be working better. Closing.
