### ISSUE TITLE
Add option to remove all files created with netsim-tools

### ISSUE THREAD

**Issue by JulioPDX** [ipspace/netsim-tools#210]
I noticed when "netlab down" is run with Containerlab, this will delete all containers and any files created by clab. This does not remove the host_vars or any additional files created by netsim-tools. It would be great to add an option to remove all the things and allow the user to start fresh. I think this will be useful, especially when individuals are just getting started with net-sim and testing out topology creation. Depending on what is created there could be host_vars left over from previous deployments. Thank you.

**Comment by JulioPDX** [comment]
Yup, understood. Just extra stuffs laying around. It bugs me.. :smirk:

**Comment by ipspace** [comment]
@JulioPDX: Took me longer than expected... life intervened ;) Hope you'll like it.
