### ISSUE TITLE
CSR1000v custom image build doesn't accept version

### ISSUE THREAD

**Issue by kbreit** [ipspace/netsim-tools#211]
I'm using CSR1000v to create a new image. I ran the `netlab libvirt package csr imagename.qcow2` command, pasted the config, saved, and exited. Eventually the script asks me for a version but doesn't note details of the version number rules. To be safe, I wrote `1` and it failed.

```
=========================
Importing the Vagrant box
=========================
Your Vagrant box is ready to be imported. We just need a few
bits of information to tag it properly so you can have multiple
Vagrant boxes (different software versions) for the same network
device.


Enter box version: 1
Creating box metadata in box.json


Importing Vagrant box
=====================

==> box: Loading metadata for box 'box.json'
    box: URL: file:///home/ubuntu/images/cisco/csr1000v/17.03.04a/box.json
==> box: Adding box 'cisco/csr1000v' (v1) for provider: libvirt
Traceback (most recent call last):
	22: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:231:in `<main>'
	21: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:290:in `cli'
	20: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/cli.rb:67:in `execute'
	19: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/box/command/root.rb:66:in `execute'
	18: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/box/command/add.rb:78:in `execute'
	17: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	16: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	15: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	14: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	13: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	12: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_add.rb:127:in `call'
	11: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_add.rb:292:in `add_from_metadata'
	10: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_add.rb:324:in `box_add'
	 9: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/box_collection.rb:280:in `find'
	 8: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/box_collection.rb:456:in `with_collection_lock'
	 7: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/box_collection.rb:456:in `synchronize'
	 6: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/box_collection.rb:457:in `block in with_collection_lock'
	 5: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/box_collection.rb:294:in `block in find'
	 4: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/box_collection.rb:294:in `map'
	 3: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/box_collection.rb:298:in `block (2 levels) in find'
	 2: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/version.rb:215:in `initialize': Malformed version number string libvirt (ArgumentError)
Error executing vagrant box add box.json:
  Command '['vagrant', 'box', 'add', 'box.json']' returned non-zero exit status 1.


Failed to add Vagrant box. Fix the error(s) and use "vagrant box add box.json" to add it.
```

**Comment by ipspace** [comment]
Interesting challenge. Have to explain the version number better.

As you entered a number, it was interpreted as a number (not string) in JSON, and that tripped Vagrant. Use IOS version (like 17.03.04).

Another bug to squash: the JSON value should always be a string.

**Comment by ipspace** [comment]
... btw, as that's the last step in the process, you could edit box.json manually and rerun "vagrant box add box.json"

**Comment by kbreit** [comment]
I updated the box.json file and it seemed to work. But ensuring it is always a string is probably a good check somewhere.

**Comment by petercrocker** [comment]
I’ve been burned before by having a system where you inter-mingle running some things as root and other as the user. I had to burn it all down and start over. Remove vagrant (sudo apt remove vagrant), install again, install the boxes again, _all_ as the user, not root! Alternately you can `sudo chown -R <username>:<username> ~<username> and sometimes that sorts things out. But sounds like you’re in that borked state!

**Comment by ipspace** [comment]
But wait, there's more... Vagrant boxes are installed into home directory and the disks are the copied into libvirt system volume where they're used as the snapshots for VM images.

If you create a new box with the same version, the image in the libvirt volume will NOT get replaced (you don't want to know how long it took me to troubleshoot that). Also, if you delete the box, the libvirt image will not be deleted. If you delete the box and create another box with the same version number... you get the idea.

**Comment by ipspace** [comment]
> But sounds like you’re in that borked state!

A drop of antimatter and a new VM?

**Comment by kbreit** [comment]
Is there an Ansible role (I know how you love Ansible!) for deploying netsim-tools?

**Comment by ipspace** [comment]
> As you entered a number, it was interpreted as a number (not string) in JSON, and that tripped Vagrant. Use IOS version (like 17.03.04).

Added an explanation to "netlab libvirt package" command, but my off-the-cuff diagnosis was wrong: the version number is always a string, so the error was probably caused by running "vagrant box add" as root.

> Another bug to squash: the JSON value should always be a string.

There's no bug to squash. JSON value is a string.
