### ISSUE TITLE
It's time we make sure "interfaces" list is always present in node data

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#213]
There are so many cases where we have to use `for n in node.interfaces|default([])` in Jinja2 templates. Let's set the **interfaces** list to [] unless it's created during link processing phase.

**Comment by jbemmel** [comment]
This code tries to do that: https://github.com/ipspace/netsim-tools/blob/dev/netsim/augment/links.py#L118

...but it's only invoked when there are interfaces to be added. Simple patch could fix that, let me see
