### ISSUE TITLE
Documentation implies port forwarding is enabled by default

### ISSUE THREAD

**Issue by kbreit** [ipspace/netsim-tools#217]
This is related to https://netsim-tools.readthedocs.io/en/latest/tutorials.html?highlight=forwarding#start-the-virtual-devices

> The easiest way to start the lab is to execute [netlab up](https://netsim-tools.readthedocs.io/en/latest/netlab/up.html) command which:
> 
>     Creates Vagrantfile or clab.yml, and Ansible inventory files;
> 
>     Starts the devices with vagrant up or containerlab deploy command
> 
>     Configures the devices with netlab initial command.

> Start the lab with vagrant up ...
```
==> r1: Forwarding ports...
    r1: 22 (guest) => 2001 (host) (adapter 1)
    r1: 80 (guest) => 8001 (host) (adapter 1)
    r1: 830 (guest) => 3001 (host) (adapter 1)
```

Based on the documentation, when I run `netlab up` it should run `vagrant up` and automatically do port forwarding so these devices are available outside of localhost. However, I don't see those messages and iptables isn't showing any forwarding rules. Do I need to manually enable port forwarding or should this be configured already?

**Comment by ipspace** [comment]
That tutorial is written for either VirtualBox or Containerlab environment (see https://netsim-tools.readthedocs.io/en/latest/tutorials.html#creating-lab-topology-file). Port forwarding is used by VirtualBox, but not by libvirt.
