### ISSUE TITLE
Enabling a protocol to run just on the loopback interface

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#222]
I started working on the VRF module and decided to implement BGP- and OSPF in the VRF as well. There's just a tiny little problem: even if I disable OSPF on all core links (because I want to run IS-IS as the global IGP), OSPF is still configured in the global routing table because of loopback interface.

So I'm wondering: does it make sense to enable an IGP when it's not configured on any interface but the loopback?

@jbemmel: would that break any of your examples?
@ssasso @petercrocker: any other concerns?

**Comment by ssasso** [comment]
IMHO it does not make any sense to have only a loopback on the IGP - unless that is required for code simplicity/compatibility - or unless I'm missing sth else.

**Comment by petercrocker** [comment]
It’s technically possible, but more of a corner case to me. I don’t see any concerns I can add here, so you’re call Ivan.

**Comment by ipspace** [comment]
Implemented in #226
