### ISSUE TITLE
Graph "glitches" for "BGP-free Core" topology

### ISSUE THREAD

**Issue by ssasso** [ipspace/netsim-tools#240]
While working on a simple "BGP-free Core" topology, I noticed that the graph output is not "formally" correct.

![outfile_wrong](https://user-images.githubusercontent.com/852093/162419395-cb328869-4aa6-4c47-8acb-f56ab03ad2da.png)

In fact, not using the *bgp* module on the node *p1* removes all its info about AS & Co.

The graph is correct if I include the *bgp* module on the node *p1* - but this will of course generate also the config for BGP, which is unwanted.

![outfile_correct](https://user-images.githubusercontent.com/852093/162419391-d2c37474-efa0-4109-85a8-e7648aade973.png)

**Comment by ssasso** [comment]
Quick suggestion:
it seems the "grouping" is performed in the function:

https://github.com/ipspace/netsim-tools/blob/d1b137c0fc4097675c1a0b863598061f65cf67f7/netsim/outputs/graph.py#L68

So a quick fix could be:

- Do not check for *bgp* module; instead check only if *bgp.as* is defined for the node.
- Allow to populate *bgp.as* on the node even if the *bgp* module is not used (this should be already possible, btw)

?

**Comment by ipspace** [comment]
Yeah, that's the only way to do it at the moment, I guess it's time to update the documentation ;)

I could also use groups (if defined) instead of AS. Any other ideas?

**Comment by ssasso** [comment]
IMHO it would be great to allow grouping in the graphs, with specific groups instead of the AS (are graph nested groups even possible in that case?)

**Comment by ipspace** [comment]
IIRC, nested groups work in GraphViz, and they're already implemented in _netsim-tools_. However, you could also define overlapping groups, and I have to figure out how that would work with GraphViz.
