### ISSUE TITLE
Use UDP tunnels for libvirt P2P links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#263]
VLAN code had to break the 'p2p' versus 'lan' link type that was used to create UDP links in libvirt Vagrantfile -- we have to use the 'lan' model on interfaces with access VLANs to ensure we're consistently using the 'prefix + node.id' addressing scheme across the VLAN segment that can span multiple links.

The side effect of that change is that we're getting P2P links modeled as Linux bridges in Vagrantfile, and that would break any L2 control plane protocol. Ignoring LACP for the moment, even STP wouldn't work across a VLAN (hooray, forwarding loops!!!)

To fix this challenge, we have to change the "tunnel or bridge" code in libvirt provider transformation code or in Vagrantfile Jinja2 template to check the number of nodes attached to a link, not the link type.

**Comment by ipspace** [comment]
Note to @ssasso: Vagrantfile is generated from interface data (not link data like containerlab template), so we'd have to rely on neighbor information being correct... but the neighbor list contains every node attached to the VLAN (not link) on non-VLAN nodes attached to access VLANs.

The only safe way is to add **libvirt.iftype** attribute to links and interfaces in the provider transformation code.

**Comment by ssasso** [comment]
Setting an additional attribute won't completely fix it. In any case, to use the *libvirt tunnel*, you need to define **remote_id** and **remote_ifindex** as well.

Even without setting a **libvirt.iftype**, the followind *should* work (apart from the missing attributes):
```
{%   for gl in links %}
{%     for l in n.interfaces|default([]) if (l.virtual_interface is not defined and l.linkindex == gl.linkindex) %}

{%       if (gl.bridge is not defined) or gl.node_count==2 %}
{%         include "libvirt-tunnel.j2" %}
{%       else %}
{%         include "libvirt-bridge.j2" %}
{%       endif %}

{%     endfor %}
{%   endfor %}
```

**Comment by ipspace** [comment]
This seems to be working in the few cases I tested ;)... and the code will be stressed quite a bit before going into the next release as I'm doing most of the tests on libvirt anyway.

Feedback highly welcome.
