### ISSUE TITLE
kvm-ok tool dependency not installed (?)

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#284]
In the 'dev' branch there is a 'kvm-ok' probe, it requires the cpu-checker package on Ubuntu

(may get installed implicitly, my system was also missing 'virsh')

**Comment by ipspace** [comment]
That check has been there "forever" (starting with release 0.8 to be precise: https://github.com/ipspace/netsim-tools/commit/0e17a70550fe22b6a4c3fc5b097c4e24e1903716).

I created a fresh Ubuntu 20.04 VM today using (among other things) `netlab install libvirt` -- that installation script was copy-pasted from Ubuntu "install KVM and libvirt" documentation. Libvirt-based labs started without a hitch, so it looks like cpu-checker (which provides kvm-ok) is a dependency of one of the packages that script installs.
