### ISSUE TITLE
Feature: Add Container lab and FRR integration tests

### ISSUE THREAD

**Issue by bbros-dev** [ipspace/netsim-tools#29]
These should have landed before #27, but we weren't sure `netsim-tools` suited our purpose.
We think it does. So here they come: PR #30.

Hope that helps?

**Comment by ipspace** [comment]
Since 0e17a70550fe22b6a4c3fc5b097c4e24e1903716 netsim-tools is available as a Python package that you could use in your projects. No need to add integration tests specific to your environment.
