### ISSUE TITLE
Rewrite the VLAN module to use explicit vlan.model device flag

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#312]
After mulling this over for a while, and sleeping on it ;)

- We have to support a wide range of use cases (see #309), from simple bridging to router-on-a-stick
- We have to support devices with widely different capabilities and configuration approaches
- Everyone hates complex logic in Jinja2 templates, and it's probably better to have the complexity in Python code.

Ergo: the Python code has to create interface- and VLAN data models that are close enough to what devices expect that a platform implementer could use them without too much Jinja2 hassle.

However, the current approach to figuring out what needs to be done is broken (thanks for pointing it out, albeit a bit indirectly). We should use an explicit device flag (example: `vlan.model`) and set it to **router** or **switch**, replacing the awkward "if this attribute is defined then we go down this path, otherwise we go down that path" decisions. I will try to make the code extensible, so we'll be able to add (for example) sub-categories of switches like **l3-switch**.

I will rewrite the code in a  week or two; can't do it before then.

_Originally posted by @ipspace in https://github.com/ipspace/netsim-tools/discussions/305#discussioncomment-2903390_

**Comment by ipspace** [comment]
Implemented in 35fbf70. The new device features are described in

https://netsim-tools.readthedocs.io/en/dev/dev/config/vlan.html#device-features

@jbemmel @ssasso: I tried to figure out what the correct settings would be for SR Linux, VyOS, and RouterOS. Would appreciate any feedback you might have.

**Comment by ssasso** [comment]
@ipspace reading at the page, I personally think that the "l3-switch" model can be better described with:
`switch-like platforms that support both routed ports and switched ports, or an hybrid approach (some ports can be routed subintf, some others can be part of the switch) (example: Arista EOS, VyOS).`

I think the current description (`Switch-like platforms that support routed ports and VLAN subinterfaces on routed ports (example: Arista EOS, VyOS).`) is a bit misleading.

The other parts look good. In "my roadmap" I have the task to allow a different config mode on RouterOS, to be able to test it with physical devices supporting hardware offloading (which require a different config than the one I already did). I'll use that implementation to better verify the options.

**Comment by ipspace** [comment]
Thank you, fixed.
