### ISSUE TITLE
VRF module does not support EVPN L3 VRFs with no interfaces assigned

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#316]
The VRF module only includes 'vrfs' for a node if there is at least 1 interface assigned to the VRF. This is not the case for EVPN overlay VRFs

**Comment by jbemmel** [comment]
Consider a "pure" VXLAN router in an asymmetric IRB scenario (i.e. using L2 vnis only). It is possible to have no interfaces assigned to the VRF, only (in SR Linux terminology) mac-vrfs with a L2 vxlan interface (with associated vni) in each of them

**Comment by ipspace** [comment]
OK, I would have to see the actual device configuration, I'm pretty sure there are interfaces involved (even if they are hidden behind other constructs).

In any case, the current VRF implementation supports L3VRFs. We'll eventually get to L2VRFs, but it will probably take a while.

**Comment by ipspace** [comment]
I guess this has been addressed with the recent additions to EVPN module.
