### ISSUE TITLE
Consider moving VNI management to separate 'vxlan' module

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#317]
The 'vlan' module currently also handles VNI assignment. For EVPN use cases, VLANs are not always required.

Some pure router platforms like 'frr' don't support / need VLANs, but they do need VNI management

**Comment by ipspace** [comment]
I have no problem moving VNI assignment somewhere else (and we'll need "transport VNI range" if we ever get to symmetrical IRB with VXLAN), but the main role of VXLAN remains transporting VLANs over an IP fabric.

What would be a use case for VXLAN transport (remember that VXLAN is just a data-plane technology) without VLANs? Even if it's an interface-to-interface P2P transport, it still involves VLANs behind the scenes with implicit internal access VLAN configured on the interface, at least as soon as you get close to ASIC.

Please note I'm not saying "this doesn't make sense", I'm just trying to figure out the various potential use cases so we can come up with a meaningful data model.

**Comment by jbemmel** [comment]
I guess it's more about the mental model for me, in a sense VXLAN is a way to move away from the more traditional VLAN based interconnect model - more "modern" if you will.

I'm working on some PRs that may include some changes in this area, just wanted to get a sense of community opinions on the topic.

**Comment by ipspace** [comment]
Conclusion: VNI is primarily a VLAN-level identifier, and when used that way, it makes sense to have **vni** attribute in VLAN dictionary.

We might need VNIs in other scenarios (example: transit VNI for symmetrical IRB). When we get there, we might either extract the VNI management code from VLAN module into a common library, or use multiple VNI pools (it's not like we'd be severely limited in the VNI address space).

I also understand that the automatic assignment of VNI to every VLAN might be problematic, so I added **defaults.vlan.auto_vni** global default that controls that behavior (default: enabled). See 91a3cbffc6ba42c1e373ad2ca46afef7de9ce3d0 for details.
