### ISSUE TITLE
New VLAN attribute gets copied into link attribute

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#332]
I am trying to extend the VLAN attributes with an 'evi' attribute for the evpn module, like so:
```
vlans:
  red:
    mode: bridge
  blue:
    mode: bridge
    evi: 1234
```

However, this attribute gets copied to each link, and then triggers an invalid attribute error:
```
IncorrectValue in links: Invalid link attributes 'evi' in {'interfaces': [{'node': 'h3'}, {'vlan': {'access': 'blue'}, 'node': 's1'}], 'linkindex': 3, 'evi': 1234, 'prefix': {'ipv4': '172.16.1.0/24'}, 'type': 'lan', 'vlan_name': 'blue'}
```

Note how 'mode' does not get copied.

In general, can we modularize the definition of vlan attributes along these lines? Something similar could be done for 'vni' (vxlan module), rd/rt (vrf module), etc.

**Comment by ipspace** [comment]
Append your attribute(s) to `topology.defaults.vlan.vlan_no_propagate`. VLAN module is the only module that copies attributes into interfaces, VRF modules does not do that, and VXLAN module does not have additional data objects (yet).

Regardless of the above, EVI seems to stand for "EVPN Instance", so it might be better to use `evpn.evi` attribute.
