### ISSUE TITLE
EVPN parameters revisited

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#335]
I added EVPN support for Arista EOS in 235366030deccb33c9a4d77489520aa2d6a08895 and had to change the "what BGP sessions do we want to use" EVPN parameters to support the simplest design (IBGP over IGP) in combination with regular IPv4 transport. The new **evpn.session** list allows you to enable EVPN AF over IBGP or EBGP or both. EOS implementation enables EVPN only over IPv4 transport session, I saw no need to enable EVPN over IPv6 (that might be needed for SRv6).

I retained the **use_ibgp** parameter which sets the **evpn.session** to **[ ibgp ]** or **[ ebgp ]**, but would like to deprecate it eventually to make the implementation more structured and consistent across platforms.

The current **use_ibgp** parameter disables IPv4 AF on IBGP sessions, which breaks any setup that uses IBGP for anything but EVPN. Maybe we could use the existing **bgp.address_families** parameter to disable IPv4 AF on IPv4 IBGP transport session?

Finally, Arista EOS requires RD/RT values for each MAC VRF, so I added RD/RT defaults to EVI default value calculation. I have no idea how Nokia SR Linux maps EVI into RT/RD, maybe it will all work?

**Comment by jbemmel** [comment]
I'm ok to remove use_ibgp, I don't think anyone is using that besides myself

SR Linux by default auto-generates RT/RD based on EVI, using <AS>:<EVI> and <system IP>:<EVI> respectively (as per https://www.rfc-editor.org/rfc/rfc8365.html#section-5.1.2.1)

**Comment by jbemmel** [comment]
Should we add evpn.rd, evpn.import and evpn.export to the vlans: parameters for the evpn module?

**Comment by jbemmel** [comment]
Should we use evpn.evi here: https://github.com/ipspace/netsim-tools/blob/dev/netsim/modules/evpn.py#L38

**Comment by ipspace** [comment]
> I'm ok to remove use_ibgp, I don't think anyone is using that besides myself

Thank you. Will remove the documentation in the next commit. When you feel it's OK to remove it from the templates please do so.

> SR Linux by default auto-generates RT/RD based on EVI, using <AS>:<EVI> and <system IP>:<EVI> respectively (as per https://www.rfc-editor.org/rfc/rfc8365.html#section-5.1.2.1)

According to that section, AS:EVI auto-RT should be some weird large number (due to TYPE set to 4), but it's nice to know my AS:VLAN hack still works (because TYPE is set to 0 for VLAN ID).

**Comment by ipspace** [comment]
> Should we use evpn.evi here: https://github.com/ipspace/netsim-tools/blob/dev/netsim/modules/evpn.py#L38

RFC 8365 points us to RFC 7432 which tells us to use VLAN ID in "unique VLAN" case, but I don't really mind going one way or the other. Also, the upper 32 bits are the router ID, so it's not like the RD would have to be consistent across PE devices.
