### ISSUE TITLE
Renaming "netsim-tools" into "netlab"

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#339]
When I started developing netsim-tools I had absolutely no idea we would get as far as we got. It was meant to be a collection of tools that would help you build networking labs, not a whole-blown system with an abstraction layer supporting over a dozen protocols... so the name _netsim-tools_ seems less appropriate than it did in the past.

As the CLI interface already uses **netlab** command to do anything and everything (as opposed to the good old days when you had to run individual Ansible playbooks), it might make sense to rename the whole thing (including Python package) to **netlab**.

Thoughts?

/cc @ssasso @jbemmel @petercrocker (as I can't assign you to this issue for whatever weird reason)

**Comment by jbemmel** [comment]
Sounds good to me, I have no objections

**Comment by ssasso** [comment]
Good for me 😊

**Comment by petercrocker** [comment]
Sounds good! I'm just introducing ~~netsim-tools~~ netlab to my team so nice to have a simpler name :)

**Comment by ipspace** [comment]
So glad to hear you're all OK with this change. I will make the necessary changes when pushing out the next release. It will probably be 1.3, as there's nothing fundamentally new that would warrant 2.0 release.

Just waiting for the few EVPN PRs from @ssasso, and I have to add another nerd knob for #344.

**Comment by ipspace** [comment]
@ssasso @jbemmel: I started replacing "netsim-tools" with "netlab" in documentation (where most of the changes need to happen), and won't merge PRs until that's done (hopefully today or tomorrow).

You might have to rebase a PR if we get into merge conflicts due to these changes.

**Comment by ipspace** [comment]
This was faster than expected ;) Documentation changes are in d2052df84ba99eebac251fd83b2d88f798d94ffd, hopefully I got them all.

@ssasso @jbemmel: Merge freeze is over ;)

**Comment by petercrocker** [comment]
@ipspace are you going to rename the repo as well?

**Comment by ipspace** [comment]
Renaming the repository would definitely break everyone's **git remote** setup, and it's not just the 5 or so people. 25 people have forked the repository. If nothing else, it would have to be announced well in advance.

**Comment by clovehitch** [comment]
`python3 -m pip install netlab` is mentioned in the docs but that looks like it's a different package. Is the correct one still `python3 -m pip install netsim-tools`?

**Comment by ipspace** [comment]
\*\*\*\* ... it looks like someone squatted that name. Thanks a million for pointing it out -- it was available when I started thinking about this in early August.

@ssasso @jbemmel @petercrocker Any ideas for an alternate pypi package name?

**Comment by petercrocker** [comment]
Aren’t all the cool kids just dropping a few vowels from their name? I propose: `netlabbr` 🤣

In all seriousness, seems `net-lab` isn’t taken on pypi

**Comment by ipspace** [comment]
> In all seriousness, seems `net-lab` isn’t taken on pypi

Pypi wouldn't allow me to do that, so I squatted on **pynetlab** and **netlab-install** to make sure we can use one of those if we decide to go that way. Any other suggestions?

**Comment by ssasso** [comment]
I'd propose the "extended" version _networklab_ (which seems free, btw), or _ipnetlab_.

**Comment by ipspace** [comment]
Thank you! Pushed "networklab" out as well. Will keep collecting ideas until tomorrow morning, and then finalize this saga.

As for "ipnetlab", I try to keep netlab a community project and thus strictly separate from ipspace -- that's also why I keep struggling with readthedocs instead of creating another Cloudflare Pages project under ipspace.net domain.

**Comment by ipspace** [comment]
Another ginormous paperwork exercise completed: changed "netsim-tools" into "netlab" in all blog posts.

**Comment by ipspace** [comment]
@petercrocker Renaming GitHub repositories works like a charm. Renamed **netsim-tools** to **netlab** and **netsim-examples** to **netlab-examples**.

Although everything works, you might want to update your Git remotes to `ipspace/netlab`.
