### ISSUE TITLE
Add advertise_default bgp attribute (global, node, interface levels)

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#354]
At global, node and interface levels, I'd like to add an 'advertise_default' flag that - if set - causes the node to advertise a default route.
Similar to advertise_loopback

I've considered allowing 'originate' at the interface level for this purpose; it's more generic, but the resulting export policy logic quickly gets complicated

**Comment by jbemmel** [comment]
In EOS this maps to "neighbor default-originate" (for example)

**Comment by ipspace** [comment]
@ssasso: This seems like a perfect addition to ebgp.utils. Will you add it or should I?

**Comment by ssasso** [comment]
I will do it! Please assign the task to me,
(give me a couple of days)

**Comment by ssasso** [comment]
Question: I guess we'd like to handle both the *default-originate* and the *default-originate always*, isn't it?

**Comment by jbemmel** [comment]
Yes, whatever makes sense. We could do
```
default_originate: True
```
and
```
default_originate: always
```
to support both cases

**Comment by ipspace** [comment]
> Question: I guess we'd like to handle both the _default-originate_ and the _default-originate always_, isn't it?

The BGP implementations I've seen had only "default-information originate" which would unconditionally advertise the default route over a BGP session regardless of what the router had in its routing table. If there's a default route in the BGP table, it's advertised no matter what.

"default-information originate always" is usually used in OSPF meaning "advertise default route in OSPF even if the router itself does not have a default route".

I'm positive (based on recent experience 😜) there must be vendors out there that are doing totally different things...

**Comment by jbemmel** [comment]
Arista has both options: https://kevin-wang-xin.medium.com/arista-eos-bgp-neighbor-default-originate-always-85effce07933
```
[ no | default ] neighbor ( ip-address | peer-group-name ) default-originate [ route-map map-name ] [ always ]
```
always: Enforce the advertisement of a fabricated default route, irrespective of availability of other default routes.

**Comment by ssasso** [comment]
The current initial implementation I did simply used the *default-originate*.

Then I discovered Arista also has the *always* option :-D 

See: https://github.com/ssasso/netsim-tools/commit/b99909ab83e07942fc38c71b4c33915c647f5936

**Comment by ipspace** [comment]
> Yes, whatever makes sense. We could do
> 
> ```
> default_originate: True
> ```
> 
> and
> 
> ```
> default_originate: always
> ```
> 
> to support both cases

This would also be easy to use in Jinja2 templates. You could test for **bgp.default_originate** being non-false to add the **neighbor** statement, and then test whether it's equal to **always** to add the **always** option.

**Comment by ipspace** [comment]
> The current initial implementation I did simply used the _default-originate_.
> 
> Then I discovered Arista also has the _always_ option :-D

Yeah, I was surprised as well. Thank you @jbemmel for another TIL ;))
