### ISSUE TITLE
Feature: Informative test suite failures

### ISSUE THREAD

**Issue by bbros-dev** [ipspace/netsim-tools#37]
The test suite is uninformative about the test that failed and why.
Unfortunately this turns the test suite in to a time sink.

```
test_transformation.py::test_minimal_cases
  topology:1: FatalError: Virtualization provider is not defined in either "provider" or "defaults.provider" elements

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED test_transformation.py::test_transformation_cases - assert 'input:\n- ...
=================== 1 failed, 3 passed, 32 warnings in 1.76s ===================
Error: Process completed with exit code 1.
```

We haven't been able to divine the source or cause of this failure from that test message.
No doubt we are at fault.

**Comment by petercrocker** [comment]
Can you share the test file you're having a problem with? From my attempt at it today, the output of test_transformation.py gave me a diff of what it expected, and what the input file had, and it was clear where it went wrong. Or are you failing on the very first line?

```
topology:1: FatalError: Virtualization provider is not defined in either "provider" or "defaults.provider" elements
```

Could that be the issue?

**Comment by ipspace** [comment]
I got it, I really have to document the testing ideas ;)

Here's a TL&DW(Y): most of the tests are topology transformation tests - take an input file, morph it, compare the results with expected results. There are other tests that should trigger various errors (in **errors** directory).

Results of the transformation tests can change if you add new functionality (example: new default module settings), in which case you need to recreate expected results with `create-transformation-tests.sh`. It's good form to do `git diff topology` afterwards and check what changed before submitting a PR ;)

**Comment by ipspace** [comment]
Automated tests documented in e5fc4ad
