### ISSUE TITLE
netlab create issue

### ISSUE THREAD

**Issue by vpasias** [ipspace/netsim-tools#38]
Dear Ivan,

I have been working with netsim-tools for quite a while and I found it extremely helpful; thank you for making this exceptional tool available to all of us.
I have created a new ubuntu server installation for netsim-tools yesterday, following exactly the instructions at: 'https://netsim-tools.readthedocs.io/en/latest/install.html#complete-ubuntu-vm-server-installation'. However when applying the command: 'netlab create', in terms of every topology that I have tried, there is the following error result:

topology:1: IncorrectValue: Topology 'includes' element (if present) should be a list
topology:2: FatalError: Cannot proceed beyond this point due to errors, exiting

See also below the results from applying the 'netlab test' command at this new ubuntu server installation:

netlab test -v libvirt
Checking virtualization provider installation
.. executing: kvm-ok
.. executing: virsh net-list
.. executing: vagrant plugin list
.. all tests succeeded, moving on

Creating test topology file in test
... done, moving on

Step 1: creating configuration files
============================================================
topology:1: IncorrectValue: Topology 'includes' element (if present) should be a list
topology:2: FatalError: Cannot proceed beyond this point due to errors, exiting
test:1: FatalError: netlab create failed, aborting...

What could be the cause of this error?
Thank you in advance.

Best Regards,

Vasilios Pasias

**Comment by ipspace** [comment]
Thanks for reporting this!

Looks like the author of python-box released a new version that behaves "a bit" different from the previous ones. The current version is 5.4.0, I have 5.2.0 on my development machine.

Will try to figure out what went wrong (or pin the python-box version to 5.2.0 in requirements) before releasing 0.9 release later this week.

**Comment by ipspace** [comment]
Yep, python-box 5.4.0 changed **setdefaults** method which sets the **includes** element which now has an unexpected value. Debugging scheduled for tomorrow ;)

**Comment by sanooprajan** [comment]
Hi Ivan,

 I second Vasilios's comment. I came across this gem today.unfortunately i also came across the same error. is there a previous version or something we can use

**Comment by ipspace** [comment]
`sudo pip3 uninstall python-box` (or similar, depending on how you install Python modules, see also https://xkcd.com/1987/), verify the installed version is 5.4.0 before removing it.

`sudo pip3 install python-box==5.3.0`

**Comment by ipspace** [comment]
Fixed by 188b9fdd392ebf39b23a6017ca8854eb8f10132d, integrated into release 0.9.
