### ISSUE TITLE
Unable to select non-default topology for 'initial' module

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#58]
While 'netlab up' and 'netlab down' allow one to select a non-default topology file, initial only accepts the default one

**Comment by ipspace** [comment]
OK, how would you like to handle it? Using an environment variable?

**Comment by ipspace** [comment]
Forget my comment, I got it. Will fix.

**Comment by ipspace** [comment]
`netlab initial` does not need a topology file. It's just a thin wrapper around an Ansible playbook which uses Ansible inventory anyway.

Documented in 9ef070c2b5a7011b01f2ac0f822c13b839c3310f
