### ISSUE TITLE
How to choose specific devices for given nodes

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#67]
When attempting to implement the Multipath example using SROS/SRLinux:
```
jeroen@jvm:~/srlinux/netsim-examples/BGP/Multipath$ netlab create -d srlinux -p clab -s nodes.rr.device=sros -s nodes.m.device=sros
Traceback (most recent call last):
  File "/home/jeroen/srlinux/netsim-tools/netlab", line 8, in <module>
    netsim.cli.lab_commands()
  File "/home/jeroen/srlinux/netsim-tools/netsim/cli/__init__.py", line 76, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
  File "/home/jeroen/srlinux/netsim-tools/netsim/cli/create.py", line 67, in run
    read_topology.add_cli_args(topology,args)
  File "/home/jeroen/srlinux/netsim-tools/netsim/read_topology.py", line 98, in add_cli_args
    common.set_dots(topo,k.split('.'),v)
  File "/home/jeroen/srlinux/netsim-tools/netsim/common.py", line 112, in set_dots
    set_dots(b[k_list[0]],k_list[1:],v)
  File "/home/jeroen/srlinux/netsim-tools/netsim/common.py", line 112, in set_dots
    set_dots(b[k_list[0]],k_list[1:],v)
  File "/home/jeroen/srlinux/netsim-tools/netsim/common.py", line 108, in set_dots
    b[k_list[0]] = v
TypeError: 'NoneType' object does not support item assignment
```

**Comment by ipspace** [comment]
This one makes perfect sense but it's much harder -- **nodes** is a list, not a dictionary, so I'll have to write extra code to deal with that.

**Comment by ipspace** [comment]
The settings are applied to raw topology file (+ defaults) before the transformation starts. Setting node attributes works **as long as the original nodes element is a dictionary and not a list**. No code to fix, will document the caveat.

**Comment by ipspace** [comment]
Dang. There was indeed a bug in the code. When recursing through the dictionary
hierarcy, a None value (caused by a node key with no data) would trip the recursion.

Fixed that bug and updated documentation. Thanks again for pointing this out.﻿

**Comment by jbemmel** [comment]
Still some issue:
```
jeroen@jvm:~/srlinux/netsim-examples/BGP/IGP-metric$ netlab up -s defaults.device=srlinux -s nodes.pe1.device=srlinux -p clab topology-ospf.yml 
Traceback (most recent call last):
  File "/home/jeroen/srlinux/netsim-tools/netlab", line 8, in <module>
    netsim.cli.lab_commands()
  File "/home/jeroen/srlinux/netsim-tools/netsim/cli/__init__.py", line 78, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
  File "/home/jeroen/srlinux/netsim-tools/netsim/cli/up.py", line 22, in run
    topology = create.run(cli_args,'up','Create configuration files, start a virtual lab, and configure it')
  File "/home/jeroen/srlinux/netsim-tools/netsim/cli/create.py", line 67, in run
    read_topology.add_cli_args(topology,args)
  File "/home/jeroen/srlinux/netsim-tools/netsim/read_topology.py", line 98, in add_cli_args
    common.set_dots(topo,k.split('.'),v)
  File "/home/jeroen/srlinux/netsim-tools/netsim/common.py", line 194, in set_dots
    set_dots(b[k_list[0]],k_list[1:],v)
  File "/home/jeroen/srlinux/netsim-tools/netsim/common.py", line 191, in set_dots
    b[k_list[0]] = {}
  File "/home/jeroen/.local/lib/python3.9/site-packages/box/box_list.py", line 91, in __setitem__
    super(BoxList, self).__setitem__(key, value)
TypeError: list indices must be integers or slices, not str
```

**Comment by ipspace** [comment]
That topology file is structured as a _list of nodes_ and you cannot set a dictionary value in a list. Have to improve the error message.

**Comment by ipspace** [comment]
3b3524e catches and prints the exception instead of the stack dump and adds a hopefully helpful message when you're trying to set **nodes** or **links** values.

**Comment by jbemmel** [comment]
See [RFC761](https://datatracker.ietf.org/doc/html/rfc761#section-2.10) - would it be possible to convert the list into a dict to accommodate the (new) user's intent?

**Comment by ipspace** [comment]
... and results in unpredictable node IDs unless you want to sort the nodes by name. The reason I used the list in the first place was to have predictable IDs. Same for links -- having them as a list gives you predictable interface names.

I don't think that dealing with a corner case that could be solved in a minute with Notepad (restructure the **nodes** in the topology file to be a dictionary) is worth a major overhaul of the code and associated testing pains.

**Comment by jbemmel** [comment]
See https://mail.python.org/pipermail/python-dev/2017-December/151283.html - 'dict' maintains the order in which items are inserted (since Python 3.7), so you can have your predictability of IDs

I'll agree that this is more of a design principled point, but I just like the idea of being able to take someone else's topology file and refine it or customize it without having to rewrite the source. Of course one can copy&paste and then modify, but then you break the chain.

There are other ways to achieve this, for example by making the logic that parses CLI -s strings more "intelligent" and have it use list addressing or dict addressing depending on context.

**Comment by ipspace** [comment]
Figured out another way of dealing with that. Now that we can have static node IDs, I could set the node ID when converting list to dict.

**Comment by ipspace** [comment]
Migration to nodes-as-a-dictionary completed (ebe310bd7f7a1a982a8fc8c5641835f6c8ec1c51)

**Comment by jbemmel** [comment]
👍

Saw a few places with old style ‘nodes’, will send PR

**Comment by ipspace** [comment]
👍

Saw a few places with old style ‘nodes’, will send PR
That would be… surprising, considering how many tests the code runs through (have to check the coverage, but it wasn’t bad the last time I ran that).

Also, for name in nodes would still iterate over node names, and if name in nodes would still check whether the node name is correct. Also, there were a few places (in graphs, IIRC) where other things were also called nodes.

Looking forward to what you’ll find

Ivan
