### ISSUE TITLE
Multiple -v (verbose) flags not passed to sub-commands

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#68]
When running 'netlab up -vvv' to see why things were failing, I only get 'failed' because only a single '-v' flag is passed on to 'initial'

Workaround: 'netlab initial -vvv' - except the 2nd time, it worked :(

**Comment by ipspace** [comment]
Will try to figure out how to do that. If it's not complicated then it's a no-brainer. In any case, I plan to add a "debugging" document, which would probably recommend running the Ansible playbooks directly. It doesn't make sense to have intermediate wrappers when debugging stuff.

**Comment by jbemmel** [comment]
'common' currently has a Boolean flag for 'VERBOSE', I think that should be a verbosity level (int) instead. Different workflows follow different paths through the code ( e.g. 'up' doesn't seem to go via 'run()' in initial.py but invokes a shell instead )

**Comment by ipspace** [comment]
Fixed in d0e552f
