### ISSUE TITLE
Missing 'config' option at individual node level

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#69]
Through the grouping concept, one can configure properties that are applied to all nodes in the group - like 'config'

As a user, I was expecting that the same would apply for 'config' - meaning one could specify 'config' both at group level, and at individual node level ( and either both would get applied(merge), or the more specific level config only )

**Comment by ipspace** [comment]
Yeah, that would make sense. Will do.

**Comment by ipspace** [comment]
Implemented in 209ce7f

**Comment by jbemmel** [comment]
The code in “must_be_list” looks wrong?

I would expect something like “if isinstance(parent,list) …”

**Comment by ipspace** [comment]
**must_be_list** makes sure that a dictionary element becomes a list. For example...

```
config: x.j2
```

... is turned into:

```
config: [ x.j2 ]
```

To make that work, the input parameter must be a the parent element (dictionary: topology, node, link...), and the parent element is thus never a list.

Python doesn't have "pass-argument-by-reference" (effectively: pass a pointer to a value) that we'd need in this case.

**Comment by ipspace** [comment]
Added longer function description in c84838beddd24bda57f50e0f7148afd669ac2a20. Hope it makes more sense now (and thanks for pointing out I was too cryptic)

**Comment by jbemmel** [comment]
The diff on my iPhone was only showing the first few lines...but it's
better now, thanks
