### ISSUE TITLE
ipv6 loopback prefix length

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netsim-tools#70]
It appears that Netsim-Tools by default allocates /64 ipv6 addresses for loopbacks (along the lines of https://tools.ietf.org/id/draft-smith-v6ops-larger-ipv6-loopback-prefix-02.html?)

However, some platforms (like SROS) require a /128 prefix for some interfaces (like 'system')

It might be ok for a platform to only use the first /128 out of an assigned /64 range - but this should probably be documented

**Comment by ipspace** [comment]
The initial reasoning was along the lines "let's do things right and assign a /64 to every interface like they intended IPv6 to be used back in 1990s". I don't want to open that particular can of worms as long as it's just a quirk of one particular platform. In this particular case, just ignore the subnet mask when configuring IPv6 on loopbacks.

I would suggest you document that in SROS caveats.

**Comment by jbemmel** [comment]
When I use 'normal' loopback interfaces /64 works, so it's all good

It's just something I noticed - I have a habit of using /128 for loopbacks, but this helped me realize /64 everywhere may be better. Definitely worth documenting
