### ISSUE TITLE
Redesigning addressing

### ISSUE THREAD

**Issue by ipspace** [ipspace/netsim-tools#97]
Based on recent fixes and ongoing discussions (cc @jbemmel @ssasso) it's evident we need to redesign the IPv4/IPv6 addressing system. The solutions has to support at least:

* Single-stack IPv4, single-stack IPv6, and dual-stack setup
* Address pools, static link addressing, and static node addressing
* Unnumbered IPv4 and IPv6 LLA (per-protocol unnumbered)
* Unaddressed (l2only) links

Ideally, we'd have an easy migration path and retain (temporary) support for existing **unnumbered** attribute.

**Comment by ipspace** [comment]
**Test cases**

Adapt existing addressing test cases:

* IPv4-only addressing
* IPv6-only addressing
* Dual-stack addressing

Each test case should include:

* Static prefix addressing
* Static node addressing
* Node with no address on the link
* Link with no address (l2only)
* Node with static address on l2only link
* Unnumbered links
* Unnumbered nodes on numbered links
* Node with static address on unnumbered link

Integration cases should include all combinations of node addressing. It doesn't matter how we set up the addressing and topology (we're testing device configuration templates, not the transformation system) as long as we have these combinations on various links:

* no ipv4/ipv6 address
* ipv4 address only
* ipv6 address only
* dual stack setup
* unnumbered ipv4
* ipv6 LLA
* ipv4 address + ipv6 LLA
* ipv6 address + ipv4 unnumbered

Ideally we'd use a small lab with a single test device coupled with reference implementation (Cumulus Linux because it's easy to download), and in the perfect world someone would have written a test script that would run on Cumulus Linux and check the implementation correctness.

**Comment by ipspace** [comment]
**Proposed solution**

* A link could get its prefixes from an addressing pool (default pool for link type or specified with **role** attribute)
* A link could have static prefix specified in **prefix** attribute

Prefix pools and static prefixes could have:

* ipv4 and/or ipv6 attributes
* be an empty dictionary (pool) or _False_ (prefix) to indicate l2only link

IPv4 and IPv6 attributes specified in **prefix** link attribute or a pool could be:

* a CIDR prefix
* boolean value (_True_/_False_)
* _None_ (which is equivalent to _False_). The reason to support _None_ is to allow YAML markup **ipv4:** or **ipv6:**

CIDR prefix specifies numbered pool. _True_ specifies unnumbered interface. _False_ or _None_ is used solely to overwrite inherited defaults (needed for IPv6-only networks with standard address pools).

Nodes can have static IPv4 or IPv6 addresses specified with **ipv4** or **ipv6** node-on-link attribute. **ipv4** and **ipv6** node-on-link attributes can also have _True_ (unnumbered) or _False_ (no address) values.

**Transformation into interface data**

* Most of the code is unchanged, we need to take care to propagate prefix-or-boolean from pools to link prefixes
* False values of **ipv4** and **ipv6** are removed from pools and prefixes as early as possible. They are also removed from the interface data -- if an interface has an address family attribute, that address family should be configured on the interface.

**Addition to node data**

Some existing templates (ios.j2) use weird logic to figure out whether IPv4 or IPv6 is enabled. We should add **af** attribute to node data and set **af.ipv4** and **af.ipv6** as needed at the end of link/interface processing. We might be able to use the same attributes in routing protocol modules, which would remove the need for EIGRP and IS-IS python code.

**Support for existing unnumbered attribute**

* Unnumbered attribute can be specified in a prefix pool or on a link.
* Unnumbered link is translated into **ipv4: True** + **ipv6: True** interface data based on the address families that are present on **loopback** interface (in the **loopback** address pool).

**Device configuration templates**

Configuration templates for all devices that support unnumbered links would have to be rewritten. Current templates are following this template:

```
interface {{ l.ifname }}
{% if l.ipv4 is defined %}
 ip address
{% endif %}
{% if l.ipv6 is defined %}
 ipv6 address
{% endif %}
{% ip l.unnumbered is defined %}
  ip unnumbered
  ipv6 enable
{% endif %}
```

New templates would have to use something along these lines:

```
interface {{ l.ifname }}
{% if l.ipv4 is defined %}
{%   if l.ipv4|ipv4 %}
 ip address
{%   else %}
 ip unnumbered
{%   endif %}
{% endif %}
{% if l.ipv6 is defined %}
{%   if l.ipv6|ipv6 %}
 ipv6 address
{%.  else %}
  ipv6 enable
{%   endif %}
{% endif %}
```

**Checking device capabilities**

We should add an attribute to **devices** defaults to indicate whether a device supports IPv4 or IPv6 unnumbered interfaces and check those capabilities at the end of link processing, otherwise we're risking broking configurations when using unnumbered links on devices that do not support them.

We didn't have that problem in the past because we used a different attribute for unnumbered links, whereas now we'd be overloading the meaning of **l.ipv4** and **l.ipv6** attribute.

**Comment by ipspace** [comment]
Comments or ideas @jbemmel @ssasso?

**Comment by jbemmel** [comment]
In https://github.com/jbemmel/netsim-examples/tree/jvb_add_lan_example/routing/sr-isis-te there is an example of a "split" link where h1 and h2 are on the same subnet, separated by an MPLS network. I'd like to be able to model that too, i.e. define the IP prefix in 1 place and use relative (int) offsets for each host

**Comment by ipspace** [comment]
I was thinking about

```
addressing:
  prefix:
    net_1:
      ipv4: 10.42.42.0/24
      ipv6: 2001:db8:0:42::/64

links:
- r1:
  r2:
  prefix: net_1
```

This would (to be consistent with everything else) generate addresses on every node on the link.

When needing "basically addressed but with a few exceptions" you'd have to remove addresses from the L2-only nodes, for example:

```
links:
- r1:
    ipv4: False
    ipv6: False
  h1:
  prefix: net_1
```

If you'd like to have "mostly L2-only, but with a few numbered nodes" then we could go for something like

```
links:
- r1:
  h1:
    ipv4: net_1:1
  prefix: False
```

Finally, I plan to add a built-in `l2only` pool, so you could have an L2-only link with

```
links:
- r1:
  h1:
    ipv4: net_1:1
  role: l2only
```

Would this work?

**Comment by ipspace** [comment]
In case anyone is interested: I started working on this in #98

**Comment by jbemmel** [comment]
> addressing:
>   prefix:
>     net_1:
>       ipv4: 10.42.42.0/24
>       ipv6: 2001:db8:0:42::/64
> 
> links:
> - r1:
>   r2:
>   prefix: net_1

> Would this work?

There can be other attributes besides ipv4/v6 prefixes that need to be correlated across multiple links, even amongst multiple l2-only links, so imho grouping only on named prefixes would be too limited.

An alternative:
```
link_groups: # or "subnets"
- name: net_1
  addressing:
    ipv4: 10.42.42.0/24
    ipv6: 2001:db8:0:42::/64
  macsec:
   cak: xyz
   cak_name: abcd
```

**Comment by ipspace** [comment]
I like the idea, and we can use it later to implement named VLANs (with VLAN attribute) or VNIs (VLAN + VNI attribute). **subnets** makes more sense than **link_groups** to me (when someone says 'link group' I immediately think of SRLG).

It would make more sense to make it a dictionary hashed by name though.

**Comment by ssasso** [comment]
I like the idea of "**subnets**" as well, which potentially can be referenced by both _links_ and _nodes_ (i.e. when it comes to VLAN SVIs definitions, which should be done at node level - but I think we could discuss it better when/if VLANs are going to be implemented).

**Comment by ssasso** [comment]
Also, it could be nice to support "extra_attributes" at subnet level (which are transparent to the netsim, but can be useful inside the ansible templates - like it's done on global and link level).

**Comment by ipspace** [comment]
> Also, it could be nice to support "extra_attributes" at subnet level (which are transparent to the netsim, but can be useful inside the ansible templates - like it's done on global and link level).

Absolutely.

**Comment by ipspace** [comment]
#98 is merged into **dev**. Have to copy the **subnet** discussion into another issue, then I'm closing this one.

Tomorrow... new year is starting in 35 minutes ;)

**Comment by ipspace** [comment]
Subnet discussion moved into #103, closing this one.
